#!/bin/bash
# Generated by DS VCF 9.1 Automated Deployment Lab Scriptgrep -qxF 'validation.disable.network.connectivity.check=true' /etc/vmware/vcf/domainmanager/application.properties || echo 'validation.disable.network.connectivity.check=true' >> /etc/vmware/vcf/domainmanager/application.properties
grep -qxF 'nsxt.mtu.validation.skip=true' /etc/vmware/vcf/domainmanager/application.properties || echo 'nsxt.mtu.validation.skip=true' >> /etc/vmware/vcf/domainmanager/application.properties
grep -qxF 'vsan.esa.sddc.managed.disk.claim=true' /etc/vmware/vcf/domainmanager/application.properties || echo 'vsan.esa.sddc.managed.disk.claim=true' >> /etc/vmware/vcf/domainmanager/application.properties
grep -qF 'lcm.depot.adapter.httpsEnabled=false' /opt/vmware/vcf/lcm/lcm-app/conf/application-prod.properties || sed -i -e "/lcm.depot.adapter.port=.*/a lcm.depot.adapter.httpsEnabled=false" /opt/vmware/vcf/lcm/lcm-app/conf/application-prod.properties
echo 'y' | /opt/vmware/vcf/operationsmanager/scripts/cli/sddcmanager_restart_services.sh
systemctl restart lcm
