#!/bin/bash
# Generated by William Lam's VCF 9 Automated Deployment Lab Script

sed -i -e "s|lcm.depot.adapter.port=.*|lcm.depot.adapter.port=80|" /opt/vmware/vcf/lcm/lcm-app/conf/application-prod.properties
sed -i -e "/lcm.depot.adapter.port=.*/a lcm.depot.adapter.httpsEnabled=false" /opt/vmware/vcf/lcm/lcm-app/conf/application-prod.properties
systemctl stop lcm
systemctl start lcm